### PR TITLE
Revert "Revert "feat: Write out emojis to system instead of copying""

### PR DESCRIPTION
**Pull request by tomershvueli**
I was getting some weirdness where I couldn't merge in my changes from the `write-moji` branch because technically your `master` was ahead since the 2 PR's were merged. So I'm created a revert-revert-merge into the `macos` branch. I believe this gets you what you wanted!

### CODE REVIEW

**Comment by virejdasani** [comment]
Thanks a ton! Going ahead with the merge 🎉

**Comment by virejdasani** [comment]
I'll have a new updated version out by the end of the week. Just have to cross off some TODO's. You'll get an alert in Geniemoji when I roll out the update 👍

**Comment by tomershvueli** [comment]
@virejdasani perfect, thanks for your help throughout this feature!

**Comment by virejdasani** [comment]
Thank you for implementing it 💯

**Comment by virejdasani** [comment]
@tomershvueli, I packaged the app for MacOS and updated it in the releases pane. There is a bug after packaging the app. The writemoji functionality no longer works! It works if you run the app via `npm start` but not after you make the executable file. You can check out the updated app (where writemoji is implemented but doesn't work) [here](https://github.com/virejdasani/Geniemoji/releases/download/v5.0.0/Geniemoji-MacOS.zip) or you can build the app by cloning this repo, going to `app/macos/` and typing `npm run pack-darwin-x64`

**Comment by virejdasani** [comment]
@tomershvueli, The update has been published!
Download [here](https://github.com/virejdasani/Geniemoji/releases)

**Pull request merged**
